name: Build

# Trigger the workflow on push or pull request
on: [push]

jobs:
  build:
    
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Generate avalonia-native.h
      run: |
        export PATH="`pwd`/sdk:$PATH"
        cd src/tools/MicroComGenerator; dotnet run -f net6.0 -c Release -i ../../avn.idl --cpp ../../../inc/avalonia-native.h
      
    - name: Build with XCode
      run: xcodebuild -sdk macosx -configuration Release -workspace src/native/Avalonia.Native.OSX.xcodeproj/project.xcworkspace -scheme Avalonia.Native.OSX build -derivedDataPath ./
      
    - name: Copy dylib
      run: |
        mkdir lib
        cp Build/Products/Release/libAvalonia.Native.OSX.dylib lib/libAvaloniaNative.dylib
      
    - name: Upload dylib
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dylib
        path: lib/libAvaloniaNative.dylib
      
    - name: Build with dotnet
      run: dotnet pack Modern.WindowKit.Backend.Mac.sln -c Release

    - name: Upload NuGet
      uses: actions/upload-artifact@v1.0.0
      with:
        name: NuGet Package
        path: src/Modern.WindowKit.Backend.Mac/bin/Release/*.nupkg
